# Generated by Django 6.0 on 2025-12-24 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
