# Generated by Django 6.0 on 2026-01-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +1234567890)', max_length=20, null=True),
        ),
    ]
