# Generated by Django 6.0 on 2026-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exercise_bookingsettings_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
