# Generated by Django 6.0 on 2026-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_memberprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='enable_auto_whatsapp_reminders',
            field=models.BooleanField(default=False, help_text='Automatically send WhatsApp payment reminders'),
        ),
    ]
