# Generated by Django 6.0 on 2026-01-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_brandingconfig_enable_auto_whatsapp_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='whatsapp_reminder_days_before',
            field=models.PositiveIntegerField(default=7, help_text='Send reminder X days before the due date'),
        ),
    ]
