# Generated by Django 6.0 on 2026-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingconfig',
            name='twilio_account_sid',
            field=models.CharField(blank=True, help_text='Twilio Account SID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='twilio_auth_token',
            field=models.CharField(blank=True, help_text='Twilio Auth Token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='brandingconfig',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, help_text='Twilio WhatsApp Number (e.g., whatsapp:+14155238886)', max_length=50, null=True),
        ),
    ]
